
name: Publish the documentation

on:
  workflow_dispatch:

  push:
    branches:
    - main
  
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b # v2.3.1
        with:
          persist-credentials: false

      - name: Set up Python 3.11
        uses: actions/setup-python@0f07f7f756721ebd886c2462646a35f78a8bc4de # v1.2.4
        with:
          python-version: 3.11

      - name: Build the documentation with Sphinx
        run: |
          pip install -e '.[dev]'
          sphinx-build -b html docs docs/build/html
          
      - name: Publish the documentation
        uses: JamesIves/github-pages-deploy-action@e80c869f0057899fc2cd28819b5bbe9de890524a # 3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/build/html
          CLEAN: true